/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Controller;
import domain.Order;
import domain.OrderDetail;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author jekm
 */
public class DataSourceDemoFrame extends javax.swing.JFrame {

    /**
     * Creates new form DataSourceDemoFrame
     */
    private Controller c = Controller.getInstance();

    public DataSourceDemoFrame() {
        initComponents();
        jComboBoxOno.setModel(createComboModel(c.getAllOno()));
    }

    public DefaultComboBoxModel createComboModel(ArrayList list) {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < list.size(); i++) {
            model.addElement(list.get(i));
        }
        return model;
    }

    private void clearOrderFields() {
        jTextFieldOrderNo.setText("");
        jTextFieldCustomerNo.setText("");
        jTextFieldEmplNo.setText("");
        jTextFieldProductNo.setText("");
        jTextFieldQuantity.setText("");
        jTextAreaOrderDetails.setText("");
        jLabelStatus.setText("");
    }

    private void clearOrderDetailFields() {
        jTextFieldProductNo.setText("");
        jTextFieldQuantity.setText("");
        jLabelStatus.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelOrderNo = new javax.swing.JLabel();
        jLabelCustomerNo = new javax.swing.JLabel();
        jLabelEmployeeNo = new javax.swing.JLabel();
        jLabelOrderDetails = new javax.swing.JLabel();
        jLabelProductNo = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jTextFieldOrderNo = new javax.swing.JTextField();
        jTextFieldCustomerNo = new javax.swing.JTextField();
        jTextFieldEmplNo = new javax.swing.JTextField();
        jTextFieldProductNo = new javax.swing.JTextField();
        jTextFieldQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOrderDetails = new javax.swing.JTextArea();
        jButtonGetOrder = new javax.swing.JButton();
        jButtonNewOrder = new javax.swing.JButton();
        jButtonNewOrderdetail = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jButtonUpdateOrder = new javax.swing.JButton();
        jButtonDeleteOrder = new javax.swing.JButton();
        jButtonUpdateQty = new javax.swing.JButton();
        jButtonDeleteProduct = new javax.swing.JButton();
        jComboBoxOno = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelOrderNo.setText("Order No");

        jLabelCustomerNo.setText("Customer No");

        jLabelEmployeeNo.setText("Employee No");

        jLabelOrderDetails.setText("Order Details");

        jLabelProductNo.setText("Product No");

        jLabelQuantity.setText("Quantity");

        jTextFieldOrderNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrderNoActionPerformed(evt);
            }
        });

        jTextAreaOrderDetails.setColumns(20);
        jTextAreaOrderDetails.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOrderDetails);

        jButtonGetOrder.setText("Get Order");
        jButtonGetOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetOrderActionPerformed(evt);
            }
        });

        jButtonNewOrder.setText("New Order");
        jButtonNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewOrderActionPerformed(evt);
            }
        });

        jButtonNewOrderdetail.setText("New Order Detail");
        jButtonNewOrderdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewOrderdetailActionPerformed(evt);
            }
        });

        jButtonUpdateOrder.setText("Update Order");
        jButtonUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateOrderActionPerformed(evt);
            }
        });

        jButtonDeleteOrder.setText("Delete Order");
        jButtonDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteOrderActionPerformed(evt);
            }
        });

        jButtonUpdateQty.setText("Update Qty");
        jButtonUpdateQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateQtyActionPerformed(evt);
            }
        });

        jButtonDeleteProduct.setText("Delete Product");
        jButtonDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteProductActionPerformed(evt);
            }
        });

        jComboBoxOno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldOrderNo, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(jComboBoxOno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addComponent(jButtonGetOrder))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jButtonUpdateOrder))
                            .addComponent(jLabelOrderDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelEmployeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldEmplNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonDeleteOrder))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(93, 93, 93)
                                    .addComponent(jButtonNewOrder)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelProductNo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldProductNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonDeleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNewOrderdetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonUpdateQty, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabelOrderNo))
                                .addComponent(jButtonGetOrder))
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBoxOno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabelCustomerNo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jTextFieldCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonNewOrder))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabelEmployeeNo))
                                .addComponent(jTextFieldEmplNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonDeleteOrder)))
                    .addGap(8, 8, 8)
                    .addComponent(jButtonUpdateOrder)
                    .addGap(15, 15, 15)
                    .addComponent(jLabelOrderDetails)
                    .addGap(19, 19, 19)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabelProductNo))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldProductNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdateQty)))
                    .addGap(16, 16, 16)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabelQuantity))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonNewOrderdetail))
                    .addGap(18, 18, 18)
                    .addComponent(jButtonDeleteProduct)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOrderNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrderNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrderNoActionPerformed

    private void jButtonGetOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetOrderActionPerformed
        int ono = Integer.parseInt(jTextFieldOrderNo.getText());
        clearOrderFields();
        Order o = c.getOrder(ono);
        if (o != null) {
            jTextFieldOrderNo.setText(o.getOno() + "");
            jTextFieldCustomerNo.setText(o.getCustomerNo() + "");
            jTextFieldEmplNo.setText(o.getEmployeeNo() + "");
            jTextAreaOrderDetails.setText(c.getOrderDetailsToString() + "");
        } else {
            jLabelStatus.setText("No matching order!");
        }

    }//GEN-LAST:event_jButtonGetOrderActionPerformed

    private void jButtonNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewOrderActionPerformed
            TestForm tf = new TestForm();
            tf.setVisible(true);
            tf.setAlwaysOnTop(true);
//        int cno = Integer.parseInt(jTextFieldCustomerNo.getText());
//        int eno = Integer.parseInt(jTextFieldEmplNo.getText());
//        clearOrderFields();
//        Order o = c.createNewOrder(cno, eno, null, null);
//        if (o != null) {
//            jTextFieldOrderNo.setText(o.getOno() + "");
//            jTextFieldCustomerNo.setText(o.getCustomerNo() + "");
//            jTextFieldEmplNo.setText(o.getEmployeeNo() + "");
//            jLabelStatus.setText("New order created");
//        } else {
//            jLabelStatus.setText("No order created!");
//        }
//        jComboBoxOno.setModel(createComboModel(c.getAllOno()));
    }//GEN-LAST:event_jButtonNewOrderActionPerformed

    private void jButtonNewOrderdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewOrderdetailActionPerformed
        int partNo = Integer.parseInt(jTextFieldProductNo.getText());
        int quantity = Integer.parseInt(jTextFieldQuantity.getText());
        clearOrderDetailFields();
        boolean status = c.addOrderDetail(partNo, quantity);
        if (status) {
            jTextAreaOrderDetails.setText(c.getOrderDetailsToString() + "");
            jLabelStatus.setText("Order detail inserted");
        } else {
            jLabelStatus.setText("Order detail not inserted");
        }
    }//GEN-LAST:event_jButtonNewOrderdetailActionPerformed

    private void jButtonUpdateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateOrderActionPerformed
        int ono = Integer.parseInt(jTextFieldOrderNo.getText());
        Order o = c.getOrder(ono);
        o.setCustomer(Integer.parseInt(jTextFieldCustomerNo.getText()));
        o.setEmployee(Integer.parseInt(jTextFieldEmplNo.getText()));
        c.updateOrder(o);
    }//GEN-LAST:event_jButtonUpdateOrderActionPerformed

    private void jButtonDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteOrderActionPerformed
        int ono = Integer.parseInt(jTextFieldOrderNo.getText());
        Order o = c.getOrder(ono);
        c.deleteOrder(o);
    }//GEN-LAST:event_jButtonDeleteOrderActionPerformed

    private void jButtonUpdateQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateQtyActionPerformed
        int ono = Integer.parseInt(jTextFieldOrderNo.getText());
        int pno = Integer.parseInt(jTextFieldProductNo.getText());
        int qty = Integer.parseInt(jTextFieldQuantity.getText());
        OrderDetail od = new OrderDetail(ono, pno, qty);
        c.updateQty(od);
    }//GEN-LAST:event_jButtonUpdateQtyActionPerformed

    private void jButtonDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteProductActionPerformed
        int ono = Integer.parseInt(jTextFieldOrderNo.getText());
        int pno = Integer.parseInt(jTextFieldProductNo.getText());
        int qty = 0;
        OrderDetail od = new OrderDetail(ono, pno, qty);
        c.deleteLine(od);
    }//GEN-LAST:event_jButtonDeleteProductActionPerformed

    private void jComboBoxOnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOnoActionPerformed
        
        int ono = (int) jComboBoxOno.getSelectedItem();
        Order o = c.getOrder(ono);
        if (o != null) {
            jTextFieldOrderNo.setText(o.getOno() + "");
            jTextFieldCustomerNo.setText(o.getCustomerNo() + "");
            jTextFieldEmplNo.setText(o.getEmployeeNo() + "");
            jTextAreaOrderDetails.setText(c.getOrderDetailsToString() + "");
        } else {
            jLabelStatus.setText("No matching order!");
        }
    }//GEN-LAST:event_jComboBoxOnoActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSourceDemoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSourceDemoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSourceDemoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSourceDemoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataSourceDemoFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteOrder;
    private javax.swing.JButton jButtonDeleteProduct;
    private javax.swing.JButton jButtonGetOrder;
    private javax.swing.JButton jButtonNewOrder;
    private javax.swing.JButton jButtonNewOrderdetail;
    private javax.swing.JButton jButtonUpdateOrder;
    private javax.swing.JButton jButtonUpdateQty;
    private javax.swing.JComboBox jComboBoxOno;
    private javax.swing.JLabel jLabelCustomerNo;
    private javax.swing.JLabel jLabelEmployeeNo;
    private javax.swing.JLabel jLabelOrderDetails;
    private javax.swing.JLabel jLabelOrderNo;
    private javax.swing.JLabel jLabelProductNo;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOrderDetails;
    private javax.swing.JTextField jTextFieldCustomerNo;
    private javax.swing.JTextField jTextFieldEmplNo;
    private javax.swing.JTextField jTextFieldOrderNo;
    private javax.swing.JTextField jTextFieldProductNo;
    private javax.swing.JTextField jTextFieldQuantity;
    // End of variables declaration//GEN-END:variables
}
