/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Controller;
import domain.Order;
import java.awt.Rectangle;
import javax.swing.JButton;

/**
 *
 * @author jekm
 */
public class TransactionDemoFrame extends javax.swing.JFrame {

    private Controller c;

    /**
     * Creates new form TransactionDemoFrame
     */
    public TransactionDemoFrame() {
        initComponents();
        c = new Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonSaveCurrentOrder = new javax.swing.JButton();
        jTextFieldOrderNo = new javax.swing.JTextField();
        jTextFieldCustomerNo = new javax.swing.JTextField();
        jTextFieldEmployeeNo = new javax.swing.JTextField();
        jButtonGetOrder = new javax.swing.JButton();
        jButtonChangeCustNo = new javax.swing.JButton();
        jButtonChangeEmplNo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldProductNo = new javax.swing.JTextField();
        jTextFieldQuantity = new javax.swing.JTextField();
        jButtonAddOrderDetail = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabelStatusDisplay = new javax.swing.JLabel();
        jLabelCurrentOrderDisplay = new javax.swing.JLabel();
        jButtonNewOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOrderDetailsDisplay = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButtonDeleteOrder = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Current order");

        jLabel2.setText("Order No");

        jLabel3.setText("Customer No");

        jLabel4.setText("Employee No");

        jButtonSaveCurrentOrder.setText("Save Current Order");
        jButtonSaveCurrentOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveCurrentOrderActionPerformed(evt);
            }
        });

        jTextFieldOrderNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrderNoActionPerformed(evt);
            }
        });

        jButtonGetOrder.setText("Get Order");
        jButtonGetOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetOrderActionPerformed(evt);
            }
        });

        jButtonChangeCustNo.setText("Change Cust No");
        jButtonChangeCustNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeCustNoActionPerformed(evt);
            }
        });

        jButtonChangeEmplNo.setText("Change Empl No");
        jButtonChangeEmplNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeEmplNoActionPerformed(evt);
            }
        });

        jLabel5.setText("Product No");

        jLabel6.setText("Quantity");

        jButtonAddOrderDetail.setText("Add Order Detail");
        jButtonAddOrderDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddOrderDetailActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabelStatusDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCurrentOrderDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonNewOrder.setText("New Order");
        jButtonNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewOrderActionPerformed(evt);
            }
        });

        jTextAreaOrderDetailsDisplay.setColumns(20);
        jTextAreaOrderDetailsDisplay.setRows(5);
        jTextAreaOrderDetailsDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextAreaOrderDetailsDisplay);

        jLabel7.setText("Order Details");

        jButtonDeleteOrder.setText("Delete Order");
        jButtonDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteOrderActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelStatusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelCurrentOrderDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldEmployeeNo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                                .addComponent(jTextFieldProductNo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                                .addComponent(jTextFieldOrderNo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                                .addComponent(jTextFieldCustomerNo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonChangeEmplNo)
                                    .addComponent(jButtonChangeCustNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAddOrderDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonGetOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonNewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonDeleteOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSaveCurrentOrder)))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelCurrentOrderDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGetOrder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChangeCustNo)
                    .addComponent(jButtonDeleteOrder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmployeeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChangeEmplNo)
                    .addComponent(jButtonNewOrder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProductNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddOrderDetail))
                .addGap(18, 18, 18)
                .addComponent(jLabelStatusDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveCurrentOrder)
                    .addComponent(jButtonReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOrderNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrderNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrderNoActionPerformed

    private void jButtonGetOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetOrderActionPerformed
        int ono = Integer.parseInt(jTextFieldOrderNo.getText());
        clearOrderFields();
        Order o = c.getOrder(ono);
        if (o != null) {
            jLabelCurrentOrderDisplay.setText(o.toString());
            jTextAreaOrderDetailsDisplay.setText(o.detailsToString());
        } else {
            jLabelStatusDisplay.setText("Could not get Order!");
        }
    }//GEN-LAST:event_jButtonGetOrderActionPerformed

    private void jButtonChangeCustNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeCustNoActionPerformed
        int cno = Integer.parseInt(jTextFieldCustomerNo.getText());
        clearOrderFields();
        Order o = c.changeCnoForOrder(cno);
        if (o != null) {
            jLabelCurrentOrderDisplay.setText(o.toString());
            jTextAreaOrderDetailsDisplay.setText(o.detailsToString());
        } else {
            jLabelStatusDisplay.setText("Fail!");
        }
    }//GEN-LAST:event_jButtonChangeCustNoActionPerformed

    private void jButtonChangeEmplNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeEmplNoActionPerformed
        int eno = Integer.parseInt(jTextFieldEmployeeNo.getText());
        clearOrderFields();
        Order o = c.changeEnoForOrder(eno);
        if (o != null) {
            jLabelCurrentOrderDisplay.setText(o.toString());
            jTextAreaOrderDetailsDisplay.setText(o.detailsToString());
        } else {
            jLabelStatusDisplay.setText("Fail!");
        }
    }//GEN-LAST:event_jButtonChangeEmplNoActionPerformed

    private void jButtonAddOrderDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddOrderDetailActionPerformed
        int partNo = Integer.parseInt(jTextFieldProductNo.getText());
        int quantity = Integer.parseInt(jTextFieldQuantity.getText());
        clearOrderDetailFields();
        boolean status = c.addOrderDetail(partNo, quantity);
        if (status) {
            jTextAreaOrderDetailsDisplay.setText(c.getOrderDetailsToString());
            jLabelStatusDisplay.setText("Order detail inserted");
        } else {
            jLabelStatusDisplay.setText("Order detail not inserted");
        }
    }//GEN-LAST:event_jButtonAddOrderDetailActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        clearOrderFields();
        clearOrderDetailFields();
        jLabelCurrentOrderDisplay.setText("");
        jTextAreaOrderDetailsDisplay.setText("");
        c.resetOrder();
        jLabelStatusDisplay.setText("Order reset");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonSaveCurrentOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveCurrentOrderActionPerformed
        clearOrderFields();
        clearOrderDetailFields();
        jLabelCurrentOrderDisplay.setText("");
        jTextAreaOrderDetailsDisplay.setText("");
        boolean status = c.saveOrder();
        if (status) {
            jLabelStatusDisplay.setText("Order saved");
        } else {
            jLabelStatusDisplay.setText("Order could not be saved!");
        }
    }//GEN-LAST:event_jButtonSaveCurrentOrderActionPerformed

    private void jButtonNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewOrderActionPerformed
        int cno = Integer.parseInt(jTextFieldCustomerNo.getText());
        int eno = Integer.parseInt(jTextFieldEmployeeNo.getText());
        clearOrderFields();
        Order o = c.createNewOrder(cno, eno, null, null);
        if (o != null) {
            jLabelCurrentOrderDisplay.setText(o.toString());
            jTextAreaOrderDetailsDisplay.setText(o.detailsToString());
        } else {
            jLabelStatusDisplay.setText("No order created!");
        }
    }//GEN-LAST:event_jButtonNewOrderActionPerformed

    private void jButtonDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteOrderActionPerformed
        boolean status = c.deleteOrder();
        if (!status) {
            jLabelStatusDisplay.setText("Order was not deleted");
        } else {
            jLabelStatusDisplay.setText("Order was deleted");
        }
    }//GEN-LAST:event_jButtonDeleteOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int pno = Integer.parseInt(jTextFieldProductNo.getText());
            int qty = Integer.parseInt(jTextFieldQuantity.getText());
            c.updateOrderDetail(pno, qty);
        } catch (IllegalArgumentException e) {
            jLabelStatusDisplay.setText("Please enter a number");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearOrderFields() {
        jTextFieldOrderNo.setText("");
        jTextFieldCustomerNo.setText("");
        jTextFieldEmployeeNo.setText("");
        jTextFieldProductNo.setText("");
        jTextFieldQuantity.setText("");
        jTextAreaOrderDetailsDisplay.setText("");
        jLabelStatusDisplay.setText("");
    }

    private void clearOrderDetailFields() {
        jTextAreaOrderDetailsDisplay.setText("");
        jTextFieldProductNo.setText("");
        jTextFieldQuantity.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;




                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionDemoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionDemoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionDemoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionDemoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionDemoFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddOrderDetail;
    private javax.swing.JButton jButtonChangeCustNo;
    private javax.swing.JButton jButtonChangeEmplNo;
    private javax.swing.JButton jButtonDeleteOrder;
    private javax.swing.JButton jButtonGetOrder;
    private javax.swing.JButton jButtonNewOrder;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSaveCurrentOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCurrentOrderDisplay;
    private javax.swing.JLabel jLabelStatusDisplay;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOrderDetailsDisplay;
    private javax.swing.JTextField jTextFieldCustomerNo;
    private javax.swing.JTextField jTextFieldEmployeeNo;
    private javax.swing.JTextField jTextFieldOrderNo;
    private javax.swing.JTextField jTextFieldProductNo;
    private javax.swing.JTextField jTextFieldQuantity;
    // End of variables declaration//GEN-END:variables
}
